import { Course, Student, Instructor, EnrollmentRecord, AssignmentSubmission, ActivityLog, PlatformSettings } from '@/types/lms';

export const INITIAL_SETTINGS: PlatformSettings = {
  portalName: 'Lumokido LMS Admin',
  organizationName: 'Lumokido Academy of Technology',
  supportEmail: 'admin@lumokido.in',
  primaryColor: '#4f46e5',
  passGradePercentage: 70,
  allowSelfRegistration: true,
  enableCertificates: true,
  notifyOnSubmissions: true,
  notifyOnEnrollment: true,
  maintenanceMode: false,
};

export const INITIAL_INSTRUCTORS: Instructor[] = [
  {
    id: 'inst-1',
    name: 'Dr. Sarah Jenkins',
    email: 'sarah.jenkins@lumokido.in',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    specialty: 'Full-Stack & Cloud Architecture',
    coursesCount: 3,
    totalStudents: 1420,
    rating: 4.9,
    status: 'active',
    bio: 'Former principal engineer at AWS with 12+ years of distributed systems experience.',
    joinedDate: '2024-01-15',
  },
  {
    id: 'inst-2',
    name: 'Alex Rivera',
    email: 'alex.rivera@lumokido.in',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    specialty: 'UI/UX & Product Design',
    coursesCount: 2,
    totalStudents: 980,
    rating: 4.8,
    status: 'active',
    bio: 'Lead product designer previously at Figma and Stripe, passionate about design systems.',
    joinedDate: '2024-03-10',
  },
  {
    id: 'inst-3',
    name: 'Kavita Menon',
    email: 'kavita.m@lumokido.in',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    specialty: 'AI & Data Science',
    coursesCount: 4,
    totalStudents: 2150,
    rating: 4.95,
    status: 'active',
    bio: 'AI researcher and author specializing in LLMs, Neural Networks, and PyTorch.',
    joinedDate: '2023-11-01',
  },
  {
    id: 'inst-4',
    name: 'Marcus Chen',
    email: 'marcus.c@lumokido.in',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    specialty: 'Algorithms & System Design',
    coursesCount: 2,
    totalStudents: 850,
    rating: 4.7,
    status: 'on_leave',
    bio: 'Ex-Google staff engineer, competitive programming coach and technical interviewer.',
    joinedDate: '2024-05-20',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'crs-1',
    title: 'Modern Full-Stack Next.js & React 19',
    code: 'CS-401',
    description: 'Master server components, server actions, optimistic UI, Turbopack, and high-performance full-stack web applications.',
    category: 'Development',
    level: 'Advanced',
    instructorId: 'inst-1',
    instructorName: 'Dr. Sarah Jenkins',
    instructorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&auto=format&fit=crop&q=80',
    price: 129,
    duration: '38h 45m',
    status: 'published',
    enrolledStudents: 624,
    rating: 4.9,
    createdAt: '2025-10-12',
    modules: [
      { id: 'm1', title: 'React 19 Hooks & Compiler Mechanics', lessonsCount: 6, duration: '4h 15m' },
      { id: 'm2', title: 'Next.js App Router & Server Components', lessonsCount: 8, duration: '6h 30m' },
      { id: 'm3', title: 'Database Integration with Prisma & Postgres', lessonsCount: 10, duration: '8h 00m' },
      { id: 'm4', title: 'Authentication, Security & Production Deployment', lessonsCount: 7, duration: '5h 45m' },
    ],
  },
  {
    id: 'crs-2',
    title: 'Generative AI & LLM Application Engineering',
    code: 'AI-502',
    description: 'Build production-ready LLM pipelines with RAG, vector embeddings, LangChain, semantic search, and autonomous agents.',
    category: 'Data & AI',
    level: 'Intermediate',
    instructorId: 'inst-3',
    instructorName: 'Kavita Menon',
    instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&auto=format&fit=crop&q=80',
    price: 199,
    duration: '44h 20m',
    status: 'published',
    enrolledStudents: 890,
    rating: 4.95,
    createdAt: '2025-11-04',
    modules: [
      { id: 'm1', title: 'Foundations of Modern Transformers & Attention', lessonsCount: 5, duration: '4h 00m' },
      { id: 'm2', title: 'Vector Embeddings & Hybrid Semantic Search', lessonsCount: 7, duration: '6h 15m' },
      { id: 'm3', title: 'RAG Architecture & Graph RAG Workflows', lessonsCount: 9, duration: '8h 30m' },
      { id: 'm4', title: 'Autonomous Multi-Agent Orchestration', lessonsCount: 8, duration: '7h 10m' },
    ],
  },
  {
    id: 'crs-3',
    title: 'Enterprise UI/UX & Design Systems with Figma',
    code: 'DS-201',
    description: 'End-to-end design systems architecture, tokens, atomic components, micro-interactions, and developer handoff.',
    category: 'Design',
    level: 'Beginner',
    instructorId: 'inst-2',
    instructorName: 'Alex Rivera',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=600&auto=format&fit=crop&q=80',
    price: 89,
    duration: '26h 10m',
    status: 'published',
    enrolledStudents: 540,
    rating: 4.8,
    createdAt: '2025-12-01',
    modules: [
      { id: 'm1', title: 'Design Token Taxonomy & Colors', lessonsCount: 4, duration: '3h 30m' },
      { id: 'm2', title: 'Figma Auto-Layout & Component Variants', lessonsCount: 8, duration: '6h 45m' },
      { id: 'm3', title: 'Accessibility & WCAG 2.2 Standards', lessonsCount: 5, duration: '4h 20m' },
    ],
  },
  {
    id: 'crs-4',
    title: 'Distributed Cloud Systems & Kubernetes on AWS',
    code: 'OPS-303',
    description: 'Architecting resilient cloud native workloads, microservices clustering, CI/CD pipelines, and observability.',
    category: 'Development',
    level: 'Advanced',
    instructorId: 'inst-1',
    instructorName: 'Dr. Sarah Jenkins',
    instructorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    price: 159,
    duration: '32h 50m',
    status: 'draft',
    enrolledStudents: 0,
    rating: 0,
    createdAt: '2026-02-14',
    modules: [
      { id: 'm1', title: 'AWS VPC, IAM & Core Networking', lessonsCount: 6, duration: '5h 00m' },
      { id: 'm2', title: 'Kubernetes Pod Scheduling & Deployments', lessonsCount: 8, duration: '7h 30m' },
    ],
  },
  {
    id: 'crs-5',
    title: 'Product Strategy & Agile Product Management',
    code: 'PM-105',
    description: 'Roadmap planning, customer discovery, metrics that matter (North Star, OKRs), and cross-functional leadership.',
    category: 'Business',
    level: 'Intermediate',
    instructorId: 'inst-4',
    instructorName: 'Marcus Chen',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
    price: 99,
    duration: '21h 15m',
    status: 'published',
    enrolledStudents: 310,
    rating: 4.7,
    createdAt: '2025-09-18',
    modules: [
      { id: 'm1', title: 'Opportunity Solution Tree & Discovery', lessonsCount: 5, duration: '4h 10m' },
      { id: 'm2', title: 'Product Metrics & Experimentation', lessonsCount: 6, duration: '5h 15m' },
    ],
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-101',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43210',
    status: 'active',
    joinDate: '2025-10-15',
    lastActive: '10 minutes ago',
    enrolledCourses: [
      { courseId: 'crs-1', courseTitle: 'Modern Full-Stack Next.js & React 19', progress: 85, status: 'in_progress', grade: 'A', enrolledDate: '2025-10-16' },
      { courseId: 'crs-2', courseTitle: 'Generative AI & LLM Application Engineering', progress: 60, status: 'in_progress', enrolledDate: '2025-11-20' },
    ],
    completedCoursesCount: 1,
    averageProgress: 72,
  },
  {
    id: 'std-102',
    name: 'Sophia Patel',
    email: 'sophia.patel@example.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98111 22334',
    status: 'active',
    joinDate: '2025-11-01',
    lastActive: '1 hour ago',
    enrolledCourses: [
      { courseId: 'crs-3', courseTitle: 'Enterprise UI/UX & Design Systems with Figma', progress: 100, status: 'completed', grade: 'A+', enrolledDate: '2025-11-02' },
      { courseId: 'crs-1', courseTitle: 'Modern Full-Stack Next.js & React 19', progress: 45, status: 'in_progress', enrolledDate: '2026-01-10' },
    ],
    completedCoursesCount: 2,
    averageProgress: 73,
  },
  {
    id: 'std-103',
    name: 'Vikram Joshi',
    email: 'vikram.j@example.com',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    phone: '+91 97234 56789',
    status: 'active',
    joinDate: '2025-11-10',
    lastActive: '3 hours ago',
    enrolledCourses: [
      { courseId: 'crs-2', courseTitle: 'Generative AI & LLM Application Engineering', progress: 92, status: 'in_progress', grade: 'A', enrolledDate: '2025-11-12' },
    ],
    completedCoursesCount: 1,
    averageProgress: 92,
  },
  {
    id: 'std-104',
    name: 'Emily Watson',
    email: 'emily.w@example.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinDate: '2025-12-05',
    lastActive: 'Yesterday',
    enrolledCourses: [
      { courseId: 'crs-3', courseTitle: 'Enterprise UI/UX & Design Systems with Figma', progress: 30, status: 'in_progress', enrolledDate: '2025-12-06' },
      { courseId: 'crs-5', courseTitle: 'Product Strategy & Agile Product Management', progress: 78, status: 'in_progress', enrolledDate: '2026-01-04' },
    ],
    completedCoursesCount: 0,
    averageProgress: 54,
  },
  {
    id: 'std-105',
    name: 'Daniel Kim',
    email: 'daniel.k@example.com',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    status: 'inactive',
    joinDate: '2025-08-20',
    lastActive: '2 weeks ago',
    enrolledCourses: [
      { courseId: 'crs-1', courseTitle: 'Modern Full-Stack Next.js & React 19', progress: 15, status: 'dropped', enrolledDate: '2025-08-22' },
    ],
    completedCoursesCount: 0,
    averageProgress: 15,
  },
  {
    id: 'std-106',
    name: 'Pooja Nair',
    email: 'pooja.nair@example.com',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinDate: '2026-01-15',
    lastActive: 'Just now',
    enrolledCourses: [
      { courseId: 'crs-2', courseTitle: 'Generative AI & LLM Application Engineering', progress: 40, status: 'in_progress', enrolledDate: '2026-01-16' },
    ],
    completedCoursesCount: 0,
    averageProgress: 40,
  },
];

export const INITIAL_ENROLLMENTS: EnrollmentRecord[] = [
  {
    id: 'enr-1',
    studentId: 'std-101',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@example.com',
    studentAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    courseId: 'crs-1',
    courseTitle: 'Modern Full-Stack Next.js & React 19',
    category: 'Development',
    enrolledDate: '2025-10-16',
    progress: 85,
    status: 'in_progress',
    lastAccessed: 'Today at 2:30 PM',
  },
  {
    id: 'enr-2',
    studentId: 'std-102',
    studentName: 'Sophia Patel',
    studentEmail: 'sophia.patel@example.com',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    courseId: 'crs-3',
    courseTitle: 'Enterprise UI/UX & Design Systems with Figma',
    category: 'Design',
    enrolledDate: '2025-11-02',
    progress: 100,
    status: 'completed',
    lastAccessed: 'Yesterday at 6:15 PM',
  },
  {
    id: 'enr-3',
    studentId: 'std-103',
    studentName: 'Vikram Joshi',
    studentEmail: 'vikram.j@example.com',
    studentAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    courseId: 'crs-2',
    courseTitle: 'Generative AI & LLM Application Engineering',
    category: 'Data & AI',
    enrolledDate: '2025-11-12',
    progress: 92,
    status: 'in_progress',
    lastAccessed: '3 hours ago',
  },
  {
    id: 'enr-4',
    studentId: 'std-104',
    studentName: 'Emily Watson',
    studentEmail: 'emily.w@example.com',
    studentAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    courseId: 'crs-5',
    courseTitle: 'Product Strategy & Agile Product Management',
    category: 'Business',
    enrolledDate: '2026-01-04',
    progress: 78,
    status: 'in_progress',
    lastAccessed: 'Yesterday',
  },
  {
    id: 'enr-5',
    studentId: 'std-106',
    studentName: 'Pooja Nair',
    studentEmail: 'pooja.nair@example.com',
    studentAvatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    courseId: 'crs-2',
    courseTitle: 'Generative AI & LLM Application Engineering',
    category: 'Data & AI',
    enrolledDate: '2026-01-16',
    progress: 40,
    status: 'in_progress',
    lastAccessed: 'Just now',
  },
];

export const INITIAL_ASSIGNMENTS: AssignmentSubmission[] = [
  {
    id: 'asg-1',
    title: 'Module 3: Full-Stack Authentication & RBAC Implementation',
    courseId: 'crs-1',
    courseTitle: 'Modern Full-Stack Next.js & React 19',
    studentId: 'std-101',
    studentName: 'Aarav Sharma',
    studentAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    submittedAt: '2026-03-02 14:22',
    dueDate: '2026-03-05 23:59',
    status: 'pending',
    score: null,
    maxScore: 100,
    feedback: null,
    attachmentName: 'auth_rbac_solution.zip',
  },
  {
    id: 'asg-2',
    title: 'RAG Pipeline with Vector DB & Semantic Caching',
    courseId: 'crs-2',
    courseTitle: 'Generative AI & LLM Application Engineering',
    studentId: 'std-103',
    studentName: 'Vikram Joshi',
    studentAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    submittedAt: '2026-03-01 18:40',
    dueDate: '2026-03-03 23:59',
    status: 'graded',
    score: 96,
    maxScore: 100,
    feedback: 'Exceptional implementation of hybrid BM25 + dense retrieval with reranking. Clean modular design!',
    attachmentName: 'rag_eval_pipeline.py',
  },
  {
    id: 'asg-3',
    title: 'Design System Tokens & Accessibility Audit in Figma',
    courseId: 'crs-3',
    courseTitle: 'Enterprise UI/UX & Design Systems with Figma',
    studentId: 'std-102',
    studentName: 'Sophia Patel',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    submittedAt: '2026-02-28 11:15',
    dueDate: '2026-02-28 23:59',
    status: 'graded',
    score: 98,
    maxScore: 100,
    feedback: 'Flawless token structure. The automated contrast checking notes were thorough and well documented.',
    attachmentName: 'figma_tokens_export.json',
  },
  {
    id: 'asg-4',
    title: 'Product Opportunity Hypothesis & PRD Draft',
    courseId: 'crs-5',
    courseTitle: 'Product Strategy & Agile Product Management',
    studentId: 'std-104',
    studentName: 'Emily Watson',
    studentAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    submittedAt: '2026-03-03 09:12',
    dueDate: '2026-03-02 23:59',
    status: 'late',
    score: null,
    maxScore: 100,
    feedback: null,
    attachmentName: 'prd_b2b_analytics.pdf',
  },
];

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act-1',
    type: 'assignment_submitted',
    title: 'New assignment submission',
    description: 'Aarav Sharma submitted "Full-Stack Authentication & RBAC"',
    timestamp: '15 mins ago',
    iconType: 'FileText',
  },
  {
    id: 'act-2',
    type: 'enrollment',
    title: 'New student enrollment',
    description: 'Pooja Nair enrolled in "Generative AI & LLM Application Engineering"',
    timestamp: '2 hours ago',
    iconType: 'UserPlus',
  },
  {
    id: 'act-3',
    type: 'graded',
    title: 'Assignment graded',
    description: 'Vikram Joshi scored 96/100 on "RAG Pipeline with Vector DB"',
    timestamp: '4 hours ago',
    iconType: 'Award',
  },
  {
    id: 'act-4',
    type: 'course_created',
    title: 'New course drafted',
    description: 'Dr. Sarah Jenkins drafted "Distributed Cloud Systems & Kubernetes on AWS"',
    timestamp: '1 day ago',
    iconType: 'BookOpen',
  },
];

export const INITIAL_BLOGS = [
  {
    id: 'blog-1',
    title: 'Mastering React 19 Server Actions and Turbopack in Production',
    slug: 'mastering-react-19-server-actions',
    excerpt: 'An in-depth guide to server actions, optimistic state transitions, and high-throughput web architecture.',
    author: 'Dr. Sarah Jenkins',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    category: 'Development',
    readTime: '6 min read',
    publishedAt: '2026-03-01',
    status: 'published' as const,
    views: 1420,
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'blog-2',
    title: 'Building Enterprise Knowledge Engines with Graph RAG and Vector DBs',
    slug: 'building-enterprise-knowledge-engines-graph-rag',
    excerpt: 'How graph traversal combines with dense embeddings to deliver context-rich generative AI responses.',
    author: 'Kavita Menon',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    category: 'Data & AI',
    readTime: '9 min read',
    publishedAt: '2026-02-24',
    status: 'published' as const,
    views: 2850,
    coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'blog-3',
    title: 'Design Token Architecture: From Figma Variables to CSS In Minutes',
    slug: 'design-token-architecture-figma-to-css',
    excerpt: 'Synchronize typography scales, responsive spacing tokens, and color modes directly to your code repository.',
    author: 'Alex Rivera',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    category: 'Design',
    readTime: '5 min read',
    publishedAt: '2026-02-18',
    status: 'published' as const,
    views: 980,
    coverImage: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'blog-4',
    title: 'Modern Product Roadmapping and Feature Prioritization Frameworks',
    slug: 'modern-product-roadmapping-frameworks',
    excerpt: 'Evaluating user feedback through RICE scoring, Kano models, and outcome-driven design.',
    author: 'Marcus Chen',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    category: 'Business',
    readTime: '7 min read',
    publishedAt: '2026-01-30',
    status: 'draft' as const,
    views: 0,
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_VIDEOS = [
  {
    id: 'vid-1',
    title: 'Full-Stack Next.js 16 Crash Course: Server Components & Cache',
    description: 'Learn how the Next.js cache layers, revalidation triggers, and client boundaries function.',
    instructor: 'Dr. Sarah Jenkins',
    duration: '45:20',
    category: 'Development',
    views: 3840,
    status: 'published' as const,
    thumbnail: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=sample1',
    createdAt: '2026-02-28',
  },
  {
    id: 'vid-2',
    title: 'LangChain & Multi-Agent Workflow Orchestration Demo',
    description: 'Live coding an autonomous research agent using tool calling and streaming responses.',
    instructor: 'Kavita Menon',
    duration: '58:15',
    category: 'Data & AI',
    views: 5120,
    status: 'published' as const,
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=sample2',
    createdAt: '2026-02-15',
  },
  {
    id: 'vid-3',
    title: 'Figma to Production Code: Design System Micro-interactions',
    description: 'Prototyping interactive buttons, spring physics, and keyboard accessibility in modern UI.',
    instructor: 'Alex Rivera',
    duration: '32:40',
    category: 'Design',
    views: 1890,
    status: 'published' as const,
    thumbnail: 'https://images.unsplash.com/photo-1542744094-24638eff58bb?w=600&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=sample3',
    createdAt: '2026-01-20',
  },
];

export const INITIAL_BOOKS = [
  {
    id: 'bk-1',
    title: 'The Clean Web Architecture Handbook (2026 Edition)',
    author: 'Dr. Sarah Jenkins',
    category: 'Development',
    pages: 340,
    format: 'PDF' as const,
    fileSize: '14.2 MB',
    downloads: 1250,
    status: 'published' as const,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    downloadUrl: '#',
    createdAt: '2026-01-10',
  },
  {
    id: 'bk-2',
    title: 'Prompt Engineering & Autonomous Agents: Real World Systems',
    author: 'Kavita Menon',
    category: 'Data & AI',
    pages: 280,
    format: 'PDF' as const,
    fileSize: '18.5 MB',
    downloads: 2410,
    status: 'published' as const,
    coverImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777f?w=600&auto=format&fit=crop&q=80',
    downloadUrl: '#',
    createdAt: '2026-02-05',
  },
  {
    id: 'bk-3',
    title: 'Design Systems Manual: Principles, Tokens & Component APIs',
    author: 'Alex Rivera',
    category: 'Design',
    pages: 215,
    format: 'EPUB' as const,
    fileSize: '9.8 MB',
    downloads: 870,
    status: 'published' as const,
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
    downloadUrl: '#',
    createdAt: '2026-02-22',
  },
];

